### ISSUE TITLE
File download error.

### ISSUE THREAD

**Issue by AnHeYi** [GitCommons/cpp-redist-nsis#1]
The script used inetc::get to download a file, but an unexpected error occurred during use, indicating a "Send Requests Error." Is there any way to troubleshoot the file?

**Comment by tcardlab** [comment]
Interesting

I've been running this in production for about a year now without issue. 
As I haven't run into this error myself, I can't say for certain what the cause might be.
(Perhaps worth noting the only difference is that I download the `/vs/16/release` rather than the `/vs/17/release` )

Possible causes:
- firewall (could be this)
- poor internet connection
- coincidental server-side issues

I usually test NSIS scripts in a fresh windows sandbox to ensure no third parties are interfering  (win defender, antivirus, firewall, etc.). Doing the same could narrow down the issue. You could also try downloading a different file to see if it's simply this endpoint that is causing you issues or a more general problem. While inetc::get is usually fine about https, there are times it is still an issue. you might want to try http just to see if it works.


Lastly, you could maybe try an alternative library like [nsis-nscurl](https://github.com/negrutiu/nsis-nscurl)



Unfortunately, I'm swamped... So, I don't have time to attempt a reproduction or implement better error handling atm...
If you figure out the cause I'd appreciate it if you let me know


> Quick-Links to inetc::get [docs](https://nsis.sourceforge.io/Inetc_plug-in) and [source](https://github.com/DigitalMediaServer/NSIS-INetC-plugin/blob/447625a39809f1df19ddeba9cb1c30e26ca741be/Contrib/Inetc/inetc.cpp#L713)

**Comment by AnHeYi** [comment]
I've found that inetc::get is unable to make `HTTPS` requests when attempting to access the network. Changing to `HTTP` requests resolves the issue.
